// This file was automatically generated by 'Kmisc::registerFunctions()'

#include <R.h>
#include <Rinternals.h>

#include <R_ext/Rdynload.h>

SEXP nro_aggregate( SEXP topo_R, SEXP bmus_R, SEXP data_R );
SEXP nro_circus( SEXP topo_R, SEXP colordata_R, SEXP labels_R, SEXP txt_R, SEXP stamp_R );
SEXP nro_colorize( SEXP name_R );
SEXP nro_figure( SEXP fname_R, SEXP data_R, SEXP bbox_R );
SEXP nro_kmeans( SEXP data_R, SEXP ncent_R );
SEXP nro_koho( SEXP seeds_R, SEXP rho_R );
SEXP nro_label( SEXP topo_R, SEXP data_R, SEXP sigma_R );
SEXP nro_match( SEXP topo_R, SEXP codebook_R, SEXP data_R );
SEXP nro_matrix( SEXP fileName_R, SEXP vars_R, SEXP kvars_R, SEXP kflag_R );
SEXP nro_permute( SEXP topo_R, SEXP bmus_R, SEXP data_R, SEXP nperm_R );
SEXP nro_train( SEXP topo_R, SEXP codebook_R, SEXP data_R );

R_CallMethodDef callMethods[]  = {
  {"nro_aggregate", (DL_FUNC) &nro_aggregate, 3},
  {"nro_circus", (DL_FUNC) &nro_circus, 5},
  {"nro_colorize", (DL_FUNC) &nro_colorize, 1},
  {"nro_figure", (DL_FUNC) &nro_figure, 3},
  {"nro_kmeans", (DL_FUNC) &nro_kmeans, 2},
  {"nro_koho", (DL_FUNC) &nro_koho, 2},
  {"nro_label", (DL_FUNC) &nro_label, 3},
  {"nro_match", (DL_FUNC) &nro_match, 3},
  {"nro_matrix", (DL_FUNC) &nro_matrix, 4},
  {"nro_permute", (DL_FUNC) &nro_permute, 4},
  {"nro_train", (DL_FUNC) &nro_train, 3},
  {NULL, NULL, 0}
};

void R_init_Numero(DllInfo *info) {
  R_registerRoutines(info, NULL, callMethods, NULL, NULL);
  R_useDynamicSymbols(info, FALSE);
}

