# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

source( "R/Import_nroCondense.R" );
source( "R/Import_nroStats.R" );

nroImportFile <- function( fileName, vars, kvars ) {
    if( nargs() < 1 ){
	stop( "Too few inputs." );
    }
    if( nargs() < 2 ){
     	vars <- c( "" );
    }
    if( nargs() < 3 ){
    	kvars <- c( "" );
    }
    
    # check file
    if( !file.exists( fileName ) ){
    	stop( "File \"", fileName, "\" cannot be accessed." );
    }

    # Check that variables are in a cell array.
    if( length( vars ) == 0 ){
    	vars <- c( "" );
    }
    if( length( kvars ) == 0 ){
    	kvars <- c( "" );
    }

    # Check that inputs are distinct.
    if( length( vars ) != length( unique( vars ) ) ){
    	stop( "Duplicate entries in VARS." );
    }
    if( length( kvars) != length( unique( kvars ) ) ){
    	stop( "Duplicate entries in KVARS." );
    }

    # obtain results
    results <- .Call('nroImportFile', fileName, vars, kvars, "@key", PACKAGE = 'Numero3');
  
    if( length( results ) == 1 ){
        stop( "Failed during processing." );
    }

    x <- t( results[[ 1 ]] );
    xvars <- results[[ 2 ]];
    xkeys <- results[[ 3 ]];
    colnames( x ) = xvars; 

    if( length( xkeys) != length( unique( xkeys ) ) ){
    	stop( "Duplicate identities exist." );
    }
    
    rownames( x ) = xkeys;

    if( length(xvars) < length(vars) ){
    	warning( "Inconsistent variables in \"", fileName, "\"");
    }

    #Clear identity data from matrix.
    mask <- which( is.element( xvars, kvars ) == TRUE )
    if( length( mask ) > 0 ){
    	x[, mask] <- NaN;
    }

    tempResults <- privateCondense( x );
    rows <- tempResults[[ 1 ]];
    cols <- tempResults[[ 2 ]];
    xvars <- xvars[ cols ];
    xkeys <- xkeys[ rows ];

    # remove identity data from matrix
    x <- x[, cols];

    return( x );
}

